[package]
name = "winnow-parser"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "winnow_parser"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { workspace = true }
winnow = "^0.7.0"
